// SilenceEvolution
// Copyright (C) 2026 Oscar Alvarez Gonzalez

pub mod admin;
pub mod console;
pub mod mysql_proxy;

use admin::*;
use console::*;
use mysql_proxy::*;

use crate::*;

use http_executor::*;

use waveless_sql::http_executor::{mysql::*, *};

pub static APP_INTERNAL_ENDPOINTS: LazyLock<Endpoints> = LazyLock::new(|| {
    // NOTE: if the main and internal databases are the same, two connections to the same database are still opened as the app's cx cannot be accessed from here due to the app's initialization order.

    Endpoints::new_unchecked(CheapVec::from_iter([
        EndpointBuilder::default()
            .id("Whoami".into())
            .databases(CheapVec::from_iter(["internal".into()]))
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("whoami".into())
                .version("internal".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(MySQLExecutorProxy::new(
                   SQLQueryWrapper::new("SELECT users.user_id, users.name, users.email, roles.role FROM |users_target_table| as users LEFT JOIN |roles_target_table| as roles ON (roles.user_id = users.user_id) WHERE (users.user_id = |user_id|)".into()).with_behaviour(SQLBehaviour::Unique).into()
                )), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Returns the current user.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("Bootstrap".into())
            .databases(CheapVec::from_iter(["internal".into()]))
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("bootstrap".into())
                .version("internal".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(MySQLExecutorProxy::new(
                   SQLQueryWrapper::Many { database: None, queries: CheapVec::from_iter(
                       [
                           SQLQuery::new("INSERT INTO |roles_target_table| (user_id, role) SELECT users.user_id, 'admin' FROM |users_target_table| as users WHERE (SELECT COUNT(*) FROM |users_target_table|) = 1".into(), false, SQLBehaviour::Permissive),
                           SQLQuery::new("SELECT roles.role FROM |roles_target_table| as roles WHERE (roles.user_id = |user_id|);".into(), true, SQLBehaviour::Unique)
                       ]
                   ) }.into()
                )), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("If there is only a single user, give it the admin role.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("ListUsers".into())
            .databases(CheapVec::from_iter(["internal".into()]))
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("users".into())
                .version("internal/admin".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(MySQLExecutorProxy::new(
                   SQLQueryWrapper::new("SELECT users.user_id, users.name, users.email, roles.role, users.password FROM |users_target_table| as users LEFT JOIN |roles_target_table| as roles ON (roles.user_id = users.user_id)".into()).into()
                )), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Returns all users.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("GetUser".into())
            .databases(CheapVec::from_iter(["internal".into()]))
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("users/{id}".into())
                .version("internal/admin".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(MySQLExecutorProxy::new(
                   SQLQueryWrapper::new("SELECT users.user_id, users.name, users.email, roles.role, users.password FROM |users_target_table| as users LEFT JOIN |roles_target_table| as roles ON (roles.user_id = users.user_id) WHERE (users.user_id = {id})".into()).with_behaviour(SQLBehaviour::Unique).into()
                )), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Returns a user given its id.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("NewUser".into())
            .databases(CheapVec::from_iter(["internal".into()]))
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("users".into())
                .version("internal/admin".into())
                .method(HttpMethod::Post)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(MySQLExecutorProxy::new(
                   SQLQueryWrapper::new("INSERT INTO |users_target_table| (name, email, password) VALUES ({name}, {email}, {password}); INSERT INTO |roles_target_table| (user_id, role) SELECT users.user_id, {role} FROM |users_target_table| as users WHERE (users.email = {email});".into()).with_include(false).into()
                )), Default::default())) // maybe `RETURNING` does not work with preparated statements?
                .body_params(CheapVec::from_vec(vec!["name".into(), "email".into(), "role".into(), "password".into()]))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Creates a new user without doing the signup flow (it won't generate a session token).".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("SetUser".into())
            .databases(CheapVec::from_iter(["internal".into()]))
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("users/{id}".into())
                .version("internal/admin".into())
                .method(HttpMethod::Put)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(MySQLExecutorProxy::new(
                   SQLQueryWrapper::new("UPDATE |users_target_table| SET name={name}, email={email}, password={password} WHERE (user_id = {id}); REPLACE INTO |roles_target_table| (user_id, role) VALUES ({id}, {role});".into()).with_include(false).into()
                )), Default::default()))
                .body_params(CheapVec::from_vec(vec!["name".into(), "email".into(), "role".into(), "password".into()]))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Modifies an existing user given its id.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("DeleteUser".into())
            .databases(CheapVec::from_iter(["internal".into()]))
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("users/{id}".into())
                .version("internal/admin".into())
                .method(HttpMethod::Delete)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(MySQLExecutorProxy::new(
                   SQLQueryWrapper::new("DELETE FROM |users_target_table| WHERE (user_id = {id})".into()).with_include(false).into()
                )), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Deletes an user given its id.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("DeleteRole".into())
            .databases(CheapVec::from_iter(["internal".into()]))
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("users/{id}/role".into())
                .version("internal/admin".into())
                .method(HttpMethod::Delete)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(MySQLExecutorProxy::new(
                   SQLQueryWrapper::new("DELETE FROM |roles_target_table| WHERE (user_id = {id})".into()).with_include(false).into()
                )), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Deletes the role of a given user id.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("ListEndpoints".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("endpoints".into())
                .version("internal".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointsManager), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Lists all endpoints of the Silence app.".into())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("GetEndpoint".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("endpoints/{endpoint_id}".into())
                .version("internal".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointsManager), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Gets an endpoint.".into())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("NewEndpoint".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("endpoints".into())
                .version("internal/admin".into())
                .method(HttpMethod::Post)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointsManager), Default::default()))
                .capture_all_params(true)
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Creates a new endpoint.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("SetEndpoint".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("endpoints/{endpoint_id}".into())
                .version("internal/admin".into())
                .method(HttpMethod::Put)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointsManager), Default::default()))
                .capture_all_params(true)
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Modifies an existing endpoint.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("DeleteEndpoint".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("endpoints/{id}".into())
                .version("internal/admin".into())
                .method(HttpMethod::Delete)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointsManager), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Deletes an existing endpoint.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("ListTests".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("tests".into())
                .version("internal/admin".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointTestsManager), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("List all tests.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("GetTest".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("tests/{test_name}".into())
                .version("internal/admin".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointTestsManager), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Gets a test.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("NewTest".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("tests".into())
                .version("internal/admin".into())
                .method(HttpMethod::Post)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointTestsManager), Default::default()))
                .capture_all_params(true)
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Creates a new test.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("SetTest".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("tests/{test_name}".into())
                .version("internal/admin".into())
                .method(HttpMethod::Put)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointTestsManager), Default::default()))
                .capture_all_params(true)
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Modifies an existing test.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("DeleteTest".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("tests/{test_name}".into())
                .version("internal/admin".into())
                .method(HttpMethod::Delete)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(EndpointTestsManager), Default::default()))
                .capture_all_params(true)
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Deletes an existing test.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("GetConfig".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("config".into())
                .version("internal/admin".into())
                .method(HttpMethod::Get)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(ConfigManager), Default::default()))
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Returns Silence app's settings.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("SetConfig".into())
            .execution_target(ExecutionTarget::Http(HttpTargetBuilder::default()
                .route("config".into())
                .version("internal/admin".into())
                .method(HttpMethod::Put)
                .execution_pipeline(ExecutionAtom::new(None, Arc::new(ConfigManager), Default::default()))
                .capture_all_params(true)
                .auto_generated(true)
                .build()
                .unwrap()
            ))
            .description("Sets Silence app's settings.".into())
            .auth(AuthBuilder::default().level(AuthLevel::Required).allowed_roles(CheapVec::from_vec(vec!["admin".into()])).build().unwrap())
            .build()
            .unwrap(),
        EndpointBuilder::default()
            .id("ConsoleStream".into())
            .execution_target(ExecutionTarget::Socket(SocketTargetBuilder::default()
                .executor(Arc::new(ConsoleStream))
                .build()
                .unwrap()
            ))
            .description("Streams Silence's console log.".into())
            .build()
            .unwrap(),
    ]))
});

/// Checks whether a given endpoint is internal.
pub fn is_endpoint_internal(endpoint: &Endpoint) -> bool {
    let ExecutionTarget::Http(http_target) = endpoint.execution_target() else {
        return true;
    };

    let Some(_) = http_target
        .execution_pipeline()
        .to_owned()
        .map(|execution_step| {
            execution_step
                .executor()
                .to_owned()
                .into_arc_any()
                .downcast::<MySQLExecutor>()
                .ok()
                .is_some()
                || execution_step
                    .executor()
                    .to_owned()
                    .into_arc_any()
                    .downcast::<MySQLExecutorProxy>()
                    .ok()
                    .is_some()
        })
    else {
        // It's trivial that if the endpoint doesn't have a MySQL executor it's because it's internal.
        return true;
    };

    if let Some(_) = APP_INTERNAL_ENDPOINTS
        .inner()
        .iter()
        .find(|_endpoint| *_endpoint.id() == endpoint.id())
    {
        return true;
    }

    return false;
}
